name: metacoag
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - click
  - biopython
  - python-igraph
  - fraggenescan
  - hmmer
  - networkx
  - scipy
  - numpy
  - pandas
  - tqdm
  - click
