name: metacoag
channels:
  - bioconda
  - defaults
dependencies:
  - python>=3.7.1
  - biopython>=1.72
  - python-igraph>=0.7.1
  - tqdm
  - networkx>=2.4
  - scipy>=1.3.1
  - numpy>=1.17.2
  - tabulate
